// Navigation icon mappings using Lucide React
export const navigationIconMap = {
  dashboard: 'LayoutDashboard',
  createCourse: 'Plus',
  browseCourses: 'BookOpen',
  myCourses: 'BookMarked',
  adminApprovals: 'CheckCircle2',
  logout: 'LogOut',
  settings: 'Settings',
  profile: 'User',
  help: 'HelpCircle',
  search: 'Search',
  menu: 'Menu',
  close: 'X',
  back: 'ChevronLeft',
  forward: 'ChevronRight',
  up: 'ChevronUp',
  down: 'ChevronDown',
  edit: 'Edit',
  delete: 'Trash2',
  save: 'Save',
  cancel: 'XCircle',
  check: 'Check',
  alert: 'AlertCircle',
  info: 'Info',
  warning: 'AlertTriangle',
  error: 'AlertOctagon',
  success: 'CheckCircle',
  loading: 'Loader',
  download: 'Download',
  upload: 'Upload',
  share: 'Share2',
  copy: 'Copy',
  star: 'Star',
  heart: 'Heart',
  thumbsUp: 'ThumbsUp',
  thumbsDown: 'ThumbsDown',
  eye: 'Eye',
  eyeOff: 'EyeOff',
  lock: 'Lock',
  unlock: 'Unlock',
  filter: 'Filter',
  sort: 'ArrowUpDown',
  calendar: 'Calendar',
  clock: 'Clock',
  mail: 'Mail',
  phone: 'Phone',
  mapPin: 'MapPin',
  externalLink: 'ExternalLink',
  home: 'Home',
  bell: 'Bell',
  cart: 'ShoppingCart',
  user: 'User',
  users: 'Users',
  layers: 'Layers',
  grid: 'Grid',
  list: 'List',
  zoomIn: 'ZoomIn',
  zoomOut: 'ZoomOut',
  maximize: 'Maximize2',
  minimize: 'Minimize2',
  fullscreen: 'Fullscreen',
  moreHorizontal: 'MoreHorizontal',
  moreVertical: 'MoreVertical',
} as const;

export type NavigationIconName = keyof typeof navigationIconMap;

export const getNavigationIcon = (
  iconName: NavigationIconName
): string => {
  return navigationIconMap[iconName];
};
